/**
 * Export Service
 * Handles export of floor plans to various formats
 */

import RNFS from 'react-native-fs';
import {Platform} from 'react-native';
import type {Plan, Room, PlacedObject} from '@types/index';
import {APP_CONFIG} from '@utils/constants';

export type ExportFormat = 'pdf' | 'svg' | 'dxf' | 'png';

export interface ExportOptions {
  format: ExportFormat;
  includeGrid?: boolean;
  includeMeasurements?: boolean;
  includeLabels?: boolean;
  scale?: number;
  quality?: 'low' | 'medium' | 'high';
}

export interface ExportResult {
  success: boolean;
  filePath?: string;
  fileSize?: number;
  error?: string;
}

// ============================================================================
// SVG Export
// ============================================================================

class SVGExporter {
  generateSVG(
    plan: Plan,
    rooms: Room[],
    objects: PlacedObject[],
    options: ExportOptions,
  ): string {
    const width = plan.width;
    const height = plan.height;
    const scale = options.scale || plan.scale;

    let svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     width="${width}"
     height="${height}"
     viewBox="0 0 ${width} ${height}">
  <title>${plan.title}</title>
  <desc>Generated by RoomDraft</desc>

  <!-- Background -->
  <rect x="0" y="0" width="${width}" height="${height}" fill="#FFFFFF"/>

`;

    // Add grid if requested
    if (options.includeGrid) {
      svg += this.generateGrid(width, height, 50);
    }

    // Add rooms
    for (const room of rooms) {
      svg += this.generateRoom(room);
    }

    // Add objects
    for (const obj of objects) {
      svg += this.generateObject(obj);
    }

    // Add measurements if requested
    if (options.includeMeasurements) {
      svg += this.generateMeasurements(rooms, scale);
    }

    // Add labels if requested
    if (options.includeLabels) {
      svg += this.generateLabels(rooms, objects);
    }

    svg += '</svg>';
    return svg;
  }

  private generateGrid(width: number, height: number, gridSize: number): string {
    let grid = '  <!-- Grid -->\n  <g id="grid" opacity="0.2">\n';

    for (let x = 0; x <= width; x += gridSize) {
      grid += `    <line x1="${x}" y1="0" x2="${x}" y2="${height}" stroke="#CCCCCC" stroke-width="0.5"/>\n`;
    }

    for (let y = 0; y <= height; y += gridSize) {
      grid += `    <line x1="0" y1="${y}" x2="${width}" y2="${y}" stroke="#CCCCCC" stroke-width="0.5"/>\n`;
    }

    grid += '  </g>\n\n';
    return grid;
  }

  private generateRoom(room: Room): string {
    const walls = JSON.parse(room.walls as any) || [];
    if (walls.length === 0) return '';

    let path = '  <g id="room-' + room.id + '">\n';
    path += `    <title>${room.name}</title>\n`;

    // Draw walls
    for (const wall of walls) {
      path += `    <line x1="${wall.start.x}" y1="${wall.start.y}" x2="${wall.end.x}" y2="${wall.end.y}" stroke="#424242" stroke-width="3"/>\n`;
    }

    path += '  </g>\n\n';
    return path;
  }

  private generateObject(obj: PlacedObject): string {
    const x = obj.positionX;
    const y = obj.positionY;
    const w = obj.width * 100; // Convert to pixels
    const h = obj.depth * 100;
    const rotation = obj.rotation;

    return `  <rect x="${x - w / 2}" y="${y - h / 2}" width="${w}" height="${h}"
            fill="#8D6E63" opacity="0.5"
            transform="rotate(${rotation} ${x} ${y})"/>\n`;
  }

  private generateMeasurements(rooms: Room[], scale: number): string {
    let measurements = '  <!-- Measurements -->\n  <g id="measurements">\n';

    for (const room of rooms) {
      const areaInMeters = room.area;
      const centerX = 500; // Simplified - should calculate actual center
      const centerY = 500;

      measurements += `    <text x="${centerX}" y="${centerY}"
                           text-anchor="middle"
                           font-size="14"
                           fill="#000000">
                           ${areaInMeters.toFixed(2)}m²
                      </text>\n`;
    }

    measurements += '  </g>\n\n';
    return measurements;
  }

  private generateLabels(rooms: Room[], objects: PlacedObject[]): string {
    let labels = '  <!-- Labels -->\n  <g id="labels">\n';

    for (const room of rooms) {
      const centerX = 500; // Simplified
      const centerY = 480;

      labels += `    <text x="${centerX}" y="${centerY}"
                        text-anchor="middle"
                        font-size="16"
                        font-weight="bold"
                        fill="#000000">
                        ${room.name}
                   </text>\n`;
    }

    labels += '  </g>\n\n';
    return labels;
  }
}

// ============================================================================
// DXF Export (CAD Format)
// ============================================================================

class DXFExporter {
  generateDXF(
    plan: Plan,
    rooms: Room[],
    objects: PlacedObject[],
    options: ExportOptions,
  ): string {
    let dxf = this.generateHeader();

    dxf += this.generateTables();

    // Entities section
    dxf += '0\nSECTION\n2\nENTITIES\n';

    // Add rooms as polylines
    for (const room of rooms) {
      dxf += this.generateRoomEntity(room);
    }

    // Add objects as blocks
    for (const obj of objects) {
      dxf += this.generateObjectEntity(obj);
    }

    dxf += '0\nENDSEC\n';

    dxf += '0\nEOF\n';
    return dxf;
  }

  private generateHeader(): string {
    return `0
SECTION
2
HEADER
9
$ACADVER
1
AC1015
9
$INSUNITS
70
4
0
ENDSEC
`;
  }

  private generateTables(): string {
    return `0
SECTION
2
TABLES
0
TABLE
2
LAYER
70
1
0
LAYER
2
WALLS
70
0
62
7
6
CONTINUOUS
0
LAYER
2
OBJECTS
70
0
62
3
6
CONTINUOUS
0
ENDTAB
0
ENDSEC
`;
  }

  private generateRoomEntity(room: Room): string {
    const walls = JSON.parse(room.walls as any) || [];
    if (walls.length === 0) return '';

    let entity = '';

    for (const wall of walls) {
      entity += `0
LINE
8
WALLS
10
${wall.start.x * 0.001}
20
${wall.start.y * 0.001}
11
${wall.end.x * 0.001}
21
${wall.end.y * 0.001}
`;
    }

    return entity;
  }

  private generateObjectEntity(obj: PlacedObject): string {
    const x = obj.positionX * 0.001;
    const y = obj.positionY * 0.001;
    const w = obj.width;
    const h = obj.depth;

    return `0
INSERT
8
OBJECTS
2
${obj.type}
10
${x}
20
${y}
41
${w}
42
${h}
50
${obj.rotation}
`;
  }
}

// ============================================================================
// PDF Export (using HTML to PDF conversion)
// ============================================================================

class PDFExporter {
  async generatePDF(
    plan: Plan,
    rooms: Room[],
    objects: PlacedObject[],
    options: ExportOptions,
  ): Promise<string> {
    // In production, use react-native-html-to-pdf or similar
    // For now, we'll create an HTML representation that can be converted

    const html = this.generateHTML(plan, rooms, objects, options);

    // Placeholder for actual PDF generation
    // In production: use react-native-html-to-pdf
    const fileName = `plan_${plan.id}_${Date.now()}.pdf`;
    const filePath = `${RNFS.DocumentDirectoryPath}/${APP_CONFIG.fileSystem.exportsDirectory}/${fileName}`;

    // Create exports directory if it doesn't exist
    const exportsDir = `${RNFS.DocumentDirectoryPath}/${APP_CONFIG.fileSystem.exportsDirectory}`;
    const dirExists = await RNFS.exists(exportsDir);
    if (!dirExists) {
      await RNFS.mkdir(exportsDir);
    }

    // Write HTML for now (in production, convert to PDF)
    await RNFS.writeFile(filePath.replace('.pdf', '.html'), html, 'utf8');

    return filePath;
  }

  private generateHTML(
    plan: Plan,
    rooms: Room[],
    objects: PlacedObject[],
    options: ExportOptions,
  ): string {
    return `
<!DOCTYPE html>
<html>
<head>
  <title>${plan.title}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    .header { text-align: center; margin-bottom: 30px; }
    .canvas { border: 1px solid #ccc; }
    .info { margin-top: 20px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${plan.title}</h1>
    <p>Generated by RoomDraft</p>
  </div>

  <svg width="${plan.width}" height="${plan.height}" viewBox="0 0 ${plan.width} ${plan.height}">
    ${new SVGExporter().generateSVG(plan, rooms, objects, options)}
  </svg>

  <div class="info">
    <h2>Plan Details</h2>
    <p>Rooms: ${rooms.length}</p>
    <p>Objects: ${objects.length}</p>
    <p>Scale: ${plan.scale} meters/pixel</p>
  </div>
</body>
</html>
`;
  }
}

// ============================================================================
// PNG Export (Screenshot)
// ============================================================================

class PNGExporter {
  async generatePNG(
    plan: Plan,
    rooms: Room[],
    objects: PlacedObject[],
    options: ExportOptions,
  ): Promise<string> {
    // In production, use react-native-view-shot or similar
    // This would capture the canvas view as an image

    const fileName = `plan_${plan.id}_${Date.now()}.png`;
    const filePath = `${RNFS.DocumentDirectoryPath}/${APP_CONFIG.fileSystem.exportsDirectory}/${fileName}`;

    // Placeholder - in production, capture actual canvas
    // For now, return the path where it would be saved

    return filePath;
  }
}

// ============================================================================
// Export Service
// ============================================================================

export class ExportService {
  private svgExporter = new SVGExporter();
  private dxfExporter = new DXFExporter();
  private pdfExporter = new PDFExporter();
  private pngExporter = new PNGExporter();

  async export(
    plan: Plan,
    rooms: Room[],
    objects: PlacedObject[],
    options: ExportOptions,
  ): Promise<ExportResult> {
    try {
      let filePath: string;
      let content: string;

      switch (options.format) {
        case 'svg':
          content = this.svgExporter.generateSVG(plan, rooms, objects, options);
          filePath = await this.saveFile(content, plan.id, 'svg');
          break;

        case 'dxf':
          content = this.dxfExporter.generateDXF(plan, rooms, objects, options);
          filePath = await this.saveFile(content, plan.id, 'dxf');
          break;

        case 'pdf':
          filePath = await this.pdfExporter.generatePDF(plan, rooms, objects, options);
          break;

        case 'png':
          filePath = await this.pngExporter.generatePNG(plan, rooms, objects, options);
          break;

        default:
          throw new Error('Unsupported export format');
      }

      const fileInfo = await RNFS.stat(filePath);

      return {
        success: true,
        filePath,
        fileSize: parseInt(fileInfo.size, 10),
      };
    } catch (error: any) {
      return {
        success: false,
        error: error.message || 'Export failed',
      };
    }
  }

  private async saveFile(
    content: string,
    planId: string,
    extension: string,
  ): Promise<string> {
    const fileName = `plan_${planId}_${Date.now()}.${extension}`;
    const exportsDir = `${RNFS.DocumentDirectoryPath}/${APP_CONFIG.fileSystem.exportsDirectory}`;

    // Create directory if it doesn't exist
    const dirExists = await RNFS.exists(exportsDir);
    if (!dirExists) {
      await RNFS.mkdir(exportsDir);
    }

    const filePath = `${exportsDir}/${fileName}`;
    await RNFS.writeFile(filePath, content, 'utf8');

    return filePath;
  }

  async deleteExport(filePath: string): Promise<boolean> {
    try {
      const exists = await RNFS.exists(filePath);
      if (exists) {
        await RNFS.unlink(filePath);
      }
      return true;
    } catch (error) {
      console.error('Failed to delete export:', error);
      return false;
    }
  }

  async shareExport(filePath: string): Promise<void> {
    // In production, use react-native-share
    // For now, just log
    console.log('Sharing export:', filePath);
  }
}

export const exportService = new ExportService();
